import { Fredoka, Inter, Lexend, Montserrat, Nunito, Outfit, Poppins, } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { ThemeProvider } from "next-themes";
import { Footer } from "@/components/footer";

const fredoka = Outfit({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});

export const metadata = {
  title: "Riven",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning className="scroll-smooth">
      <body
        className={`${fredoka.className} antialiased`}
      >
        <ThemeProvider enableSystem attribute={'class'}>
          <Navbar>
            {children}
          </Navbar>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
